layers: 0
dataset_type: imbalanced
cache: false
num_epochs: 50
output_directory: models
dataset_directory: data/aio
batch_size: 32
convolution_count: 0
logger: neptune
gpu: 0
tpu: none
balanced: 0

defaults:
  - features: degree
