dataloader:
  data_dir: data/aio
  balanced: 0
  batch_size: 16
  cache: false
  pin_memory: false
  num_workers: 6

model:
  convolution_count: 0

trainer:
  max_epochs: 50
  gpus: null

hydra:
  run:
    dir: output/${features.name}/${dataloader.balanced}-${features.readout_weights}-conv_count=${model.convolution_count}

defaults:
  - features: degree
