dataloader:
  data_dir: data/aio
  balanced: 0
  batch_size: 16
  cache: false
  pin_memory: false
  num_workers: 6

model:
  convolution_count: 0
  convolution_algorithm: GCN # Can be one of GCN, SAGE, TAG, SGConv, DotGatConv

trainer:
  max_epochs: 100
  gpus: null

hydra:
  run:
    dir: output/${model.convolution_algorithm}/${features.name}/${dataloader.balanced}-${features.readout_type}${features.readout_weights}-conv_count=${model.convolution_count}
  sweep:
    dir: output/${model.convolution_algorithm}/${features.name}
    subdir: ${dataloader.balanced}-${features.readout_type}${features.readout_weights}-conv_count=${model.convolution_count}

defaults:
  - features: degree
