layers: 0
dataset_type: imbalanced
num_epochs: 50
output_directory: models
dataset_directory: "data/processed"
batch_size: 32
convolution_count: 0
logger: neptune
gpu: none
tpu: none
balanced: 0

defaults:
  - features: degree